import { ENHANCEMENT_OPERATIONS, type AspectRatio, type AssetType, type GenerationCapability } from "@listingboost/domain";

export type TemplateDefinition = {
  id: string;
  version: number;
  name: string;
  assetType: AssetType;
  aspectRatio: AspectRatio | null;
  capability: GenerationCapability;
  config: Record<string, unknown>;
};

export const COPY_SLOTS = ["headline", "supporting_copy", "instagram_caption", "facebook_copy", "linkedin_copy", "hashtags", "cta"] as const;
export type CopySlot = (typeof COPY_SLOTS)[number];

const COPY_LIMITS: Record<CopySlot, { maxLength: number; description: string }> = {
  headline: { maxLength: 80, description: "A short headline for the listing" },
  supporting_copy: { maxLength: 400, description: "Two or three sentences of supporting marketing copy" },
  instagram_caption: { maxLength: 1200, description: "An Instagram caption" },
  facebook_copy: { maxLength: 1500, description: "A Facebook post" },
  linkedin_copy: { maxLength: 1500, description: "A professional LinkedIn post" },
  hashtags: { maxLength: 300, description: "Up to 12 relevant hashtags" },
  cta: { maxLength: 80, description: "A call to action inviting viewings" },
};

function graphic(id: string, name: string, assetType: "social_post" | "story", aspectRatio: AspectRatio, width: number, height: number): TemplateDefinition {
  return {
    id,
    version: 1,
    name,
    assetType,
    aspectRatio,
    capability: "template_render",
    config: {
      canvas: { width, height },
      imageSlot: { source: "primary_photo", fit: "cover" },
      textSlots: [
        { key: "headline", source: "copy:headline", maxLines: 2 },
        { key: "price", source: "fact:price", optional: true },
        { key: "summary", source: "fact:bedrooms_bathrooms", optional: true },
      ],
      logo: { position: "bottom-right", maxWidthRatio: 0.22 },
      cta: { source: "copy:cta" },
      colours: { from: "brand", fallback: { primary: "#1d2433", secondary: "#f6f1e8" } },
      typography: { from: "brand", fallback: { heading: "serif", body: "sans-serif" } },
    },
  };
}

export const DEFAULT_TEMPLATES: readonly TemplateDefinition[] = [
  {
    id: "enhanced-photo",
    version: 1,
    name: "Enhanced photograph",
    assetType: "enhanced_photo",
    aspectRatio: "original",
    capability: "image_enhancement",
    config: { operations: [...ENHANCEMENT_OPERATIONS] },
  },
  graphic("social-square", "Social post (square)", "social_post", "1:1", 1080, 1080),
  graphic("social-portrait", "Social post (portrait)", "social_post", "4:5", 1080, 1350),
  graphic("story", "Story", "story", "9:16", 1080, 1920),
  {
    id: "reel-slideshow",
    version: 1,
    name: "Reel (photo slideshow)",
    assetType: "reel",
    aspectRatio: "9:16",
    capability: "video_generation",
    config: { canvas: { width: 1080, height: 1920 }, secondsPerPhoto: 3, maxPhotos: 10, transition: "crossfade", mode: "slideshow" },
  },
  ...COPY_SLOTS.map(
    (slot): TemplateDefinition => ({
      id: `copy-${slot.replace(/_/g, "-")}`,
      version: 1,
      name: `Copy: ${slot.replace(/_/g, " ")}`,
      assetType: "copy",
      aspectRatio: null,
      capability: "text_generation",
      config: { slot, ...COPY_LIMITS[slot] },
    }),
  ),
];

export function findTemplate(id: string, version: number): TemplateDefinition | undefined {
  return DEFAULT_TEMPLATES.find((t) => t.id === id && t.version === version);
}

const sqlString = (value: string) => `'${value.replace(/'/g, "''")}'`;

/** Source of migrations/0002_default_templates.sql; a unit test keeps them identical. */
export function templateSeedSql(): string {
  const rows = DEFAULT_TEMPLATES.map(
    (t) =>
      `  (${sqlString(t.id)}, ${t.version}, ${sqlString(t.name)}, ${sqlString(t.assetType)}, ${t.aspectRatio ? sqlString(t.aspectRatio) : "NULL"}, ${sqlString(
        JSON.stringify({ capability: t.capability, ...t.config }),
      )}, '2026-09-25T00:00:00.000Z')`,
  );
  return [
    "-- Generated by templateSeedSql() in packages/templates. Do not edit by hand;",
    "-- template changes ship as a new version in a new migration.",
    "INSERT INTO templates (id, version, name, asset_type, aspect_ratio, config_json, created_at) VALUES",
    rows.join(",\n") + ";",
    "",
  ].join("\n");
}
