import { expect, test, type Page } from "@playwright/test";
import { strFromU8, unzipSync } from "fflate";
import { readFileSync, writeFileSync } from "node:fs";
import { validateReelVideo } from "../../packages/storage/src/video-validation";

const PHOTOS = ["tests/support/fixtures/images/photo-800x600.jpg", "tests/support/fixtures/images/photo-1080x1350.jpg"];

async function signUp(page: Page, email: string, agency = "Orchard Estates") {
  await page.goto("/signup");
  await page.getByLabel("Your name").fill("Alex Agent");
  await page.getByLabel("Agency name").fill(agency);
  await page.getByLabel("Email").fill(email);
  await page.getByLabel("Password").fill("a long enough password");
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page).toHaveURL(/\/app\/listings$/);
}

const tab = (page: Page, name: string) => page.getByRole("navigation", { name: "Listing" }).getByRole("link", { name, exact: true });

test("AT-13 full journey: sign in → property → photos → campaign → generate → review → approve → download pack", async ({ page, browser }) => {
  const email = `e2e-${Date.now()}@agency.test`;
  await signUp(page, email);

  // Sign out and back in, so the journey starts from a real sign-in.
  await page.getByRole("button", { name: "Sign out" }).click();
  await expect(page).toHaveURL(/\/signin$/);
  await page.getByLabel("Email").fill(email);
  await page.getByLabel("Password").fill("a long enough password");
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page).toHaveURL(/\/app\/listings$/);

  // Create the property with only the facts we know.
  await page.getByRole("navigation", { name: "Main" }).getByRole("link", { name: "New Listing" }).click();
  await page.getByLabel("First line of address").fill("12 Orchard Way");
  await page.getByLabel("Town").fill("Harpenden");
  await page.getByLabel("Postcode").fill("AL5 2AB");
  await page.getByLabel("Property type").selectOption("semi_detached");
  await page.getByLabel("Bedrooms").fill("3");
  await page.getByLabel("Price (£)").fill("650000");
  await page.getByLabel("Price qualifier").selectOption("guide_price");
  await page.getByLabel("Tenure").selectOption("freehold");
  await page.getByRole("button", { name: "Create listing" }).click();
  await expect(page.getByRole("heading", { level: 1, name: "12 Orchard Way, Harpenden" })).toBeVisible();
  const listingUrl = page.url();

  // Upload photographs.
  await tab(page, "Images").click();
  await page.setInputFiles("#photo-upload", PHOTOS);
  await expect(page.locator("li[data-media-id]")).toHaveCount(2);
  await expect(page.locator("li[data-media-id]").first().getByText("Primary", { exact: true })).toBeVisible();

  // Create the campaign and generate.
  await tab(page, "Overview").click();
  await page.getByRole("button", { name: "Create campaign" }).click();
  const progress = page.getByRole("list", { name: "Campaign progress" });
  await expect(progress).toBeVisible();
  await page.getByRole("button", { name: "Generate marketing" }).click();

  // Copy and graphics are generated by the queue consumer on workerd; the page polls until they are ready.
  await expect(progress.locator("li", { hasText: "Social copy" })).toContainText("Ready for review", { timeout: 45_000 });
  await expect(progress.locator("li", { hasText: "Social posts" })).toContainText("Ready for review", { timeout: 45_000 });
  await expect(progress.locator("li", { hasText: "Stories" })).toContainText("Ready for review", { timeout: 45_000 });
  await expect(progress.locator("li", { hasText: "Enhanced images" })).toContainText("Not available yet");

  // Review and approve two pieces of copy; edit one first.
  await tab(page, "Social Posts").click();
  const headline = page.getByRole("article", { name: "Headline" });
  await expect(headline).toContainText("3 bedroom semi-detached house in Harpenden");
  await headline.getByRole("button", { name: "Approve" }).click();
  await expect(headline.getByText("Approved", { exact: true })).toBeVisible();

  const cta = page.getByRole("article", { name: "Call to action" });
  await cta.getByRole("button", { name: "Edit text" }).click();
  await cta.getByRole("textbox").fill("Call Orchard Estates today to arrange your viewing.");
  await cta.getByRole("button", { name: "Save as new version" }).click();
  await expect(cta).toContainText("Version 2");
  await cta.getByRole("button", { name: "Approve" }).click();
  await expect(cta.getByText("Approved", { exact: true })).toBeVisible();

  // Approve the rendered square post; its preview is a real 1080x1080 image.
  const square = page.getByRole("article", { name: "Social post 1:1" });
  const preview = square.getByRole("img", { name: "Social post 1:1" });
  await expect.poll(() => preview.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth)).toBe(1080);
  await square.getByRole("button", { name: "Approve" }).click();
  await expect(square.getByText("Approved", { exact: true })).toBeVisible();

  // Make the slideshow Reel in this browser (WebCodecs), then approve it.
  await tab(page, "Reels").click();
  const reel = page.getByRole("article", { name: "Reel 9:16" });
  await reel.getByRole("button", { name: "Create slideshow Reel" }).click();
  await expect(reel.getByText("Ready for review", { exact: true })).toBeVisible({ timeout: 60_000 });
  await expect.poll(() => reel.locator("video").evaluate((v: HTMLVideoElement) => (v.readyState >= 1 ? Math.round(v.duration) : 0))).toBe(6);
  await reel.getByRole("button", { name: "Approve" }).click();
  await expect(reel.getByText("Approved", { exact: true })).toBeVisible();

  // Download the marketing pack and check it contains exactly the approved copy.
  await tab(page, "Marketing Pack").click();
  await expect(page.getByText("4 approved assets included", { exact: false })).toBeVisible();
  const [download] = await Promise.all([page.waitForEvent("download"), page.getByRole("link", { name: "Download marketing pack" }).click()]);
  expect(download.suggestedFilename()).toBe("12-orchard-way-harpenden-marketing-pack.zip");
  const files = unzipSync(new Uint8Array(readFileSync(await download.path())));
  expect(Object.keys(files).sort()).toEqual([
    "12-orchard-way-harpenden/Copy/cta.txt",
    "12-orchard-way-harpenden/Copy/headline.txt",
    "12-orchard-way-harpenden/README.txt",
    "12-orchard-way-harpenden/Reels/12-orchard-way-harpenden-reel.mp4",
    "12-orchard-way-harpenden/Social/12-orchard-way-harpenden-social-square.png",
  ]);
  const png = files["12-orchard-way-harpenden/Social/12-orchard-way-harpenden-social-square.png"]!;
  const view = new DataView(png.buffer, png.byteOffset);
  expect([view.getUint32(16), view.getUint32(20)]).toEqual([1080, 1080]);
  const mp4 = validateReelVideo(files["12-orchard-way-harpenden/Reels/12-orchard-way-harpenden-reel.mp4"]!, { width: 1080, height: 1920, durationSeconds: 6 });
  expect(["avc1", "vp09", "av01"]).toContain(mp4.codec);
  expect(strFromU8(files["12-orchard-way-harpenden/Copy/cta.txt"]!)).toBe("Call Orchard Estates today to arrange your viewing.\n");
  expect(strFromU8(files["12-orchard-way-harpenden/Copy/headline.txt"]!)).toBe("3 bedroom semi-detached house in Harpenden\n");

  // AT-02: another agency cannot open this listing.
  const other = await browser.newContext();
  const otherPage = await other.newPage();
  await signUp(otherPage, `e2e-other-${Date.now()}@agency.test`, "Rival Lettings");
  await otherPage.goto(listingUrl);
  await expect(otherPage.getByText("Listing not found.")).toBeVisible();
  await expect(otherPage.getByText("12 Orchard Way")).toHaveCount(0);
  await other.close();
});

/**
 * AT-22 on the real Worker runtime. The unit and integration suites run in
 * Bun; only this proves that SVG rasterising, WebP and WOFF2 decoding, static
 * preset fonts and brand rendering work on workerd.
 */
test("AT-22 brand settings: SVG and WebP logos, a WOFF2 font and the Full photo layout render on workerd", async ({ page }) => {
  await signUp(page, `e2e-brand-${Date.now()}@agency.test`, "Orchard Estates");
  // Collected from here on: before sign-up the app's own session check is a 401, which the browser logs.
  const consoleErrors: string[] = [];
  page.on("console", (message) => message.type() === "error" && consoleErrors.push(message.text()));
  await page.getByRole("navigation", { name: "Main" }).getByRole("link", { name: "Brand Settings" }).click();
  await expect(page.getByRole("heading", { level: 1, name: "Brand Settings" })).toBeVisible();
  const status = page.getByRole("status", { name: "Brand settings updates" });
  const logoGroup = page.getByRole("group", { name: "Logo" });

  // A WebP logo is converted to PNG by the libwebp decoder.
  await page.getByLabel("Upload a logo").setInputFiles("tests/support/fixtures/images/photo-800x600.webp");
  await expect(status).toContainText("converted to PNG");
  const current = logoGroup.getByRole("img", { name: "Current logo" });
  await expect.poll(() => current.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth)).toBe(800);

  // An SVG logo is safety-checked and rasterised by resvg; the WebP one becomes a previous logo.
  await page.getByLabel("Upload a logo").setInputFiles("tests/support/fixtures/logos/logo.svg");
  await expect(logoGroup.getByText("Previous logos")).toBeVisible();
  await expect.poll(() => current.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth)).toBe(2048);
  const logoResponse = await page.request.get((await current.getAttribute("src"))!);
  expect(logoResponse.headers()["content-type"]).toBe("image/png");

  // A WOFF2 font is decoded by the vendored woff2 decoder and test-rendered by satori.
  await page.getByLabel("Font file").setInputFiles({ name: "Brand Sans.woff2", mimeType: "font/woff2", buffer: readFileSync("node_modules/@fontsource/inter/files/inter-latin-400-normal.woff2") });
  await page.getByLabel(/I have the right to use this font/).check();
  await page.getByRole("button", { name: "Upload font" }).click();
  await expect(status).toContainText("Font uploaded");

  await page.getByLabel("Heading font").selectOption({ label: "Brand Sans" });
  // A preset font is read from the site's static files through the ASSETS binding.
  await page.getByLabel("Body font").selectOption({ label: "Lato" });
  await page.getByLabel("Primary colour", { exact: true }).fill("#1d2433");
  await page.getByLabel("Phone").fill("01582 760000");
  await page.getByLabel("Tone preference").fill("Warm and plain-spoken");
  await page.getByLabel("Social post (square)").selectOption({ label: "Full photo" });
  await page.getByRole("button", { name: "Save brand settings" }).click();
  await expect(status.or(page.getByRole("alert")).filter({ hasText: /\S/ })).toHaveText(/Brand settings saved/);

  // Saved values are there on return.
  await page.reload();
  await expect(page.getByLabel("Phone")).toHaveValue("01582 760000");
  await expect(page.getByLabel("Social post (square)")).toHaveValue("social-square-full");

  // AC35: at a narrow phone width and at desktop width nothing overflows sideways and Save is reachable.
  for (const [width, height] of [[390, 844], [1280, 900]] as const) {
    await page.setViewportSize({ width, height });
    expect(await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)).toBeLessThanOrEqual(0);
    for (const label of ["Agency name", "Upload a logo", "Heading font", "Font file", "Tone preference", "Story"]) {
      const box = (await page.getByLabel(label, { exact: true }).boundingBox())!;
      expect(box.x).toBeGreaterThanOrEqual(0);
      expect(box.x + box.width).toBeLessThanOrEqual(width);
    }
    const saveButton = page.getByRole("button", { name: "Save brand settings" });
    await saveButton.scrollIntoViewIfNeeded();
    await expect(saveButton).toBeInViewport();
    if (process.env.LB_SAVE_RENDERS) await page.screenshot({ path: `${process.env.LB_SAVE_RENDERS}/brand-page-${width}.png`, fullPage: true });
  }

  // Optional accessibility scan: LB_AXE_PATH=/path/to/axe.min.js. axe-core is not a project dependency,
  // so this runs only when a copy is supplied; results are written beside the renders for verify.md.
  if (process.env.LB_AXE_PATH) {
    await page.evaluate(readFileSync(process.env.LB_AXE_PATH, "utf8"));
    const results = await page.evaluate(async () => {
      const run = (globalThis as unknown as { axe: { run(context: Element, options: object): Promise<{ violations: Array<{ id: string; impact: string | null; help: string; nodes: Array<{ target: string[] }> }> }> } }).axe.run;
      const { violations } = await run(document.querySelector("main")!, { runOnly: ["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"] });
      return violations.map((v) => ({ id: v.id, impact: v.impact, help: v.help, targets: v.nodes.map((n) => n.target.join(" ")) }));
    });
    if (process.env.LB_SAVE_RENDERS) writeFileSync(`${process.env.LB_SAVE_RENDERS}/axe-brand-settings.json`, JSON.stringify(results, null, 2));
    expect(results.filter((v) => v.impact === "serious" || v.impact === "critical")).toEqual([]);
  }

  // A new campaign uses them.
  await page.getByRole("navigation", { name: "Main" }).getByRole("link", { name: "New Listing" }).click();
  await page.getByLabel("First line of address").fill("7 Mill Lane");
  await page.getByLabel("Town").fill("Harpenden");
  await page.getByLabel("Postcode").fill("AL5 2AB");
  await page.getByLabel("Property type").selectOption("detached");
  await page.getByLabel("Bedrooms").fill("4");
  await page.getByRole("button", { name: "Create listing" }).click();
  await expect(page.getByRole("heading", { level: 1, name: "7 Mill Lane, Harpenden" })).toBeVisible();
  await tab(page, "Images").click();
  await page.setInputFiles("#photo-upload", [PHOTOS[0]!]);
  await expect(page.locator("li[data-media-id]")).toHaveCount(1);
  await tab(page, "Overview").click();
  await page.getByRole("button", { name: "Create campaign" }).click();
  const progress = page.getByRole("list", { name: "Campaign progress" });
  await page.getByRole("button", { name: "Generate marketing" }).click();
  await expect(progress.locator("li", { hasText: "Social posts" })).toContainText("Ready for review", { timeout: 60_000 });
  await expect(progress.locator("li", { hasText: "Stories" })).toContainText("Ready for review", { timeout: 60_000 });

  // Both layouts rendered at full size with the logo and fonts loaded on workerd.
  await tab(page, "Social Posts").click();
  for (const [name, width, height] of [["Social post 1:1", 1080, 1080], ["Social post 4:5", 1080, 1350]] as const) {
    const preview = page.getByRole("article", { name }).getByRole("img", { name });
    await expect.poll(() => preview.evaluate((img: HTMLImageElement) => (img.complete ? [img.naturalWidth, img.naturalHeight] : null))).toEqual([width, height]);
    if (process.env.LB_SAVE_RENDERS) {
      const image = await page.request.get((await preview.getAttribute("src"))!);
      writeFileSync(`${process.env.LB_SAVE_RENDERS}/e2e-${width}x${height}.png`, await image.body());
    }
  }
  await tab(page, "Stories").click();
  const story = page.getByRole("article", { name: "Story 9:16" }).getByRole("img", { name: "Story 9:16" });
  await expect.poll(() => story.evaluate((img: HTMLImageElement) => (img.complete ? [img.naturalWidth, img.naturalHeight] : null))).toEqual([1080, 1920]);

  // No Content-Security-Policy violation or other console error along the way.
  expect(consoleErrors).toEqual([]);
});

/**
 * AT-05 / work item 004: the slideshow Reel draws photos in the browser with createImageBitmap
 * (apps/web/client/src/reel/encoder.ts), not with the Worker's renderer. A WebP photo stored before
 * WebP was refused must still decode there. New WebP photos cannot be uploaded, so this checks the
 * decode step itself in the real browser.
 */
test("AT-05 the Reel's in-browser decode step reads a WebP photo at full size", async ({ page }) => {
  await page.goto("/");
  for (const file of ["photo-800x600.webp", "photo-800x600-lossless.webp"]) {
    const base64 = Buffer.from(readFileSync(`tests/support/fixtures/images/${file}`)).toString("base64");
    const size = await page.evaluate(async (data) => {
      const binary = atob(data);
      const bytes = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
      const bitmap = await createImageBitmap(new Blob([bytes], { type: "image/webp" }));
      return [bitmap.width, bitmap.height];
    }, base64);
    expect(size).toEqual([800, 600]);
  }
});
