import { expect, test, type Page } from "@playwright/test";
import { strFromU8, unzipSync } from "fflate";
import { readFileSync } from "node:fs";

const PHOTOS = ["tests/support/fixtures/images/photo-800x600.jpg", "tests/support/fixtures/images/photo-1080x1350.jpg"];

async function signUp(page: Page, email: string, agency = "Orchard Estates") {
  await page.goto("/signup");
  await page.getByLabel("Your name").fill("Alex Agent");
  await page.getByLabel("Agency name").fill(agency);
  await page.getByLabel("Email").fill(email);
  await page.getByLabel("Password").fill("a long enough password");
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page).toHaveURL(/\/app\/listings$/);
}

const tab = (page: Page, name: string) => page.getByRole("navigation", { name: "Listing" }).getByRole("link", { name, exact: true });

test("AT-13 full journey: sign in → property → photos → campaign → generate → review → approve → download pack", async ({ page, browser }) => {
  const email = `e2e-${Date.now()}@agency.test`;
  await signUp(page, email);

  // Sign out and back in, so the journey starts from a real sign-in.
  await page.getByRole("button", { name: "Sign out" }).click();
  await expect(page).toHaveURL(/\/signin$/);
  await page.getByLabel("Email").fill(email);
  await page.getByLabel("Password").fill("a long enough password");
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page).toHaveURL(/\/app\/listings$/);

  // Create the property with only the facts we know.
  await page.getByRole("navigation", { name: "Main" }).getByRole("link", { name: "New Listing" }).click();
  await page.getByLabel("First line of address").fill("12 Orchard Way");
  await page.getByLabel("Town").fill("Harpenden");
  await page.getByLabel("Postcode").fill("AL5 2AB");
  await page.getByLabel("Property type").selectOption("semi_detached");
  await page.getByLabel("Bedrooms").fill("3");
  await page.getByLabel("Price (£)").fill("650000");
  await page.getByLabel("Price qualifier").selectOption("guide_price");
  await page.getByLabel("Tenure").selectOption("freehold");
  await page.getByRole("button", { name: "Create listing" }).click();
  await expect(page.getByRole("heading", { level: 1, name: "12 Orchard Way, Harpenden" })).toBeVisible();
  const listingUrl = page.url();

  // Upload photographs.
  await tab(page, "Images").click();
  await page.setInputFiles("#photo-upload", PHOTOS);
  await expect(page.locator("li[data-media-id]")).toHaveCount(2);
  await expect(page.locator("li[data-media-id]").first().getByText("Primary", { exact: true })).toBeVisible();

  // Create the campaign and generate.
  await tab(page, "Overview").click();
  await page.getByRole("button", { name: "Create campaign" }).click();
  const progress = page.getByRole("list", { name: "Campaign progress" });
  await expect(progress).toBeVisible();
  await page.getByRole("button", { name: "Generate marketing" }).click();

  // Copy and graphics are generated by the queue consumer on workerd; the page polls until they are ready.
  await expect(progress.locator("li", { hasText: "Social copy" })).toContainText("Ready for review", { timeout: 45_000 });
  await expect(progress.locator("li", { hasText: "Social posts" })).toContainText("Ready for review", { timeout: 45_000 });
  await expect(progress.locator("li", { hasText: "Stories" })).toContainText("Ready for review", { timeout: 45_000 });
  await expect(progress.locator("li", { hasText: "Enhanced images" })).toContainText("Not available yet");

  // Review and approve two pieces of copy; edit one first.
  await tab(page, "Social Posts").click();
  const headline = page.getByRole("article", { name: "Headline" });
  await expect(headline).toContainText("3 bedroom semi-detached house in Harpenden");
  await headline.getByRole("button", { name: "Approve" }).click();
  await expect(headline.getByText("Approved", { exact: true })).toBeVisible();

  const cta = page.getByRole("article", { name: "Call to action" });
  await cta.getByRole("button", { name: "Edit text" }).click();
  await cta.getByRole("textbox").fill("Call Orchard Estates today to arrange your viewing.");
  await cta.getByRole("button", { name: "Save as new version" }).click();
  await expect(cta).toContainText("Version 2");
  await cta.getByRole("button", { name: "Approve" }).click();
  await expect(cta.getByText("Approved", { exact: true })).toBeVisible();

  // Approve the rendered square post; its preview is a real 1080x1080 image.
  const square = page.getByRole("article", { name: "Social post 1:1" });
  const preview = square.getByRole("img", { name: "Social post 1:1" });
  await expect.poll(() => preview.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth)).toBe(1080);
  await square.getByRole("button", { name: "Approve" }).click();
  await expect(square.getByText("Approved", { exact: true })).toBeVisible();

  // Download the marketing pack and check it contains exactly the approved copy.
  await tab(page, "Marketing Pack").click();
  await expect(page.getByText("3 approved assets included", { exact: false })).toBeVisible();
  const [download] = await Promise.all([page.waitForEvent("download"), page.getByRole("link", { name: "Download marketing pack" }).click()]);
  expect(download.suggestedFilename()).toBe("12-orchard-way-harpenden-marketing-pack.zip");
  const files = unzipSync(new Uint8Array(readFileSync(await download.path())));
  expect(Object.keys(files).sort()).toEqual([
    "12-orchard-way-harpenden/Copy/cta.txt",
    "12-orchard-way-harpenden/Copy/headline.txt",
    "12-orchard-way-harpenden/README.txt",
    "12-orchard-way-harpenden/Social/12-orchard-way-harpenden-social-square.png",
  ]);
  const png = files["12-orchard-way-harpenden/Social/12-orchard-way-harpenden-social-square.png"]!;
  const view = new DataView(png.buffer, png.byteOffset);
  expect([view.getUint32(16), view.getUint32(20)]).toEqual([1080, 1080]);
  expect(strFromU8(files["12-orchard-way-harpenden/Copy/cta.txt"]!)).toBe("Call Orchard Estates today to arrange your viewing.\n");
  expect(strFromU8(files["12-orchard-way-harpenden/Copy/headline.txt"]!)).toBe("3 bedroom semi-detached house in Harpenden\n");

  // AT-02: another agency cannot open this listing.
  const other = await browser.newContext();
  const otherPage = await other.newPage();
  await signUp(otherPage, `e2e-other-${Date.now()}@agency.test`, "Rival Lettings");
  await otherPage.goto(listingUrl);
  await expect(otherPage.getByText("Listing not found.")).toBeVisible();
  await expect(otherPage.getByText("12 Orchard Way")).toHaveCount(0);
  await other.close();
});
