/**
 * Builds the vendored WOFF2 decoder in packages/ai/vendor/woff2 from the
 * pinned `woff2-encoder` dev dependency (DECISIONS D-022, spike 002).
 *
 * The package is Google's woff2 compiled with Emscripten. As shipped it cannot
 * run in a Worker, for two reasons this script removes:
 *   1. It embeds its WebAssembly as base64 and compiles it at runtime. Workers
 *      only accept precompiled modules, so the bytes are written to a .wasm
 *      file and the loader takes the module from its caller.
 *   2. Its binding layer builds one function from a string. That is replaced
 *      with an ordinary closure that does the same work.
 *
 * Each change is anchored on exact text. If the package changes, the anchor
 * is missing and the build throws instead of producing a broken decoder. A
 * unit test keeps the committed files identical to this script's output.
 *
 *   bun scripts/build-woff2-decoder.ts
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const SOURCE = join(ROOT, "node_modules/woff2-encoder/dist/decompress.js");
const OUT_DIR = join(ROOT, "packages/ai/vendor/woff2");

const WASM_PREFIX = "data:application/octet-stream;base64,";
const INVOKER_START = 'return b&&(d+="var ret = retType.fromWireType(rv)';
const INVOKER_END = "(Function,m).apply(null,h)";
const LOADER_TAIL = "let C=new Promise(A=>{I({onRuntimeInitialized(){A(this)}})});";

// Same behaviour as the generated function it replaces: convert arguments,
// call the wasm export, run destructors, convert the result.
const INVOKER =
  'return function(...args){if(args.length!==G-2)P("function "+A+" called with "+args.length+" arguments, expected "+(G-2));' +
  "var ds=l?[]:null,w=[B];for(var i=0;i<G-2;++i)w.push(I[i+2].toWireType(ds,args[i]));var rv=g.apply(null,w);" +
  "if(l)AQ(ds);else for(var i=2;i<I.length;++i)if(null!==I[i].destructorFunction)I[i].destructorFunction(w[i-1]);" +
  "if(b)return I[0].fromWireType(rv)}";

// The caller supplies the WebAssembly: a precompiled module in Workers, bytes in tests.
const LOADER =
  "export function createWoff2Module(wasm){return new Promise((resolve,reject)=>{I({instantiateWasm(imports,done){" +
  "const mod=wasm instanceof WebAssembly.Module?wasm:new WebAssembly.Module(wasm);const instance=new WebAssembly.Instance(mod,imports);" +
  "done(instance);return instance.exports},onRuntimeInitialized(){resolve(this)}}).catch(reject)})}\n";

const HEADER =
  "// GENERATED by scripts/build-woff2-decoder.ts from woff2-encoder@2.0.0 (MIT). Do not edit.\n" +
  "// Licence notices: ./NOTICES.md\n";

function once(source: string, anchor: string, label: string): number {
  const index = source.indexOf(anchor);
  if (index === -1 || source.indexOf(anchor, index + 1) !== -1) {
    throw new Error(`build-woff2-decoder: anchor for ${label} not found exactly once; woff2-encoder has changed and the patches must be reviewed`);
  }
  return index;
}

export function readWoff2Source(): string {
  return readFileSync(SOURCE, "utf8");
}

export function buildWoff2Decoder(source: string): { js: string; wasm: Uint8Array } {
  const wasmStart = once(source, `${WASM_PREFIX}AGFzbQ`, "the embedded WebAssembly") + WASM_PREFIX.length;
  const wasmEnd = source.indexOf('"', wasmStart);
  const base64 = source.slice(wasmStart, wasmEnd);
  if (wasmEnd === -1 || !/^[A-Za-z0-9+/]+=*$/.test(base64)) throw new Error("build-woff2-decoder: anchor for the embedded WebAssembly is malformed");
  let js = source.slice(0, wasmStart) + source.slice(wasmEnd);

  const invokerStart = once(js, INVOKER_START, "the string-built invoker (start)");
  const invokerEnd = once(js, INVOKER_END, "the string-built invoker (end)") + INVOKER_END.length;
  if (invokerEnd < invokerStart) throw new Error("build-woff2-decoder: anchor for the string-built invoker is out of order");
  js = js.slice(0, invokerStart) + INVOKER + js.slice(invokerEnd);

  const tail = once(js, LOADER_TAIL, "the module loader");
  js = HEADER + js.slice(0, tail) + LOADER;

  return { js, wasm: new Uint8Array(Buffer.from(base64, "base64")) };
}

if (import.meta.main) {
  const { js, wasm } = buildWoff2Decoder(readWoff2Source());
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, "woff2-decompress.js"), js);
  writeFileSync(join(OUT_DIR, "woff2-decompress.wasm"), wasm);
  console.log(`woff2 decoder written: ${js.length} bytes of JavaScript, ${wasm.length} bytes of WebAssembly`);
}
